#배포용
# 1. Node.js 이미지에서 빌드
FROM node:16-alpine AS build
WORKDIR /usr/src/app

# 패키지 설치 및 코드 복사
COPY package.json . 
RUN npm install
COPY . .
# RUN npm run build

# 2. Nginx로 배포 (React 정적 파일 서빙)
FROM nginx:latest
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
