#배포용
version: "3"

services:
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
    volumes:
    - ./client/nginx.conf:/etc/nginx/nginx.conf
    - ./client/build:/usr/share/nginx/html
    container_name: nginxcontainer
    depends_on:
      - server
    networks:
      - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server  # Node.js 서버만 빌드하는 Dockerfile 따로 생성
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.prod
    container_name: servercontainer
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    env_file:
      - ./server/.env.prod
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}' # 개발용 DB 따로 사용
    ports:
      - "3306:3306"
    container_name: dbcontainer
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
